[tortoise]
# модуль, где лежит TORTOISE_ORM
models = database.config.TORTOISE_ORM
# папка для миграций (должна существовать и быть в репозитории)
location = ./migrations
# app name из Tortoise config (обычно "models")
app = database.models